name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        es-build: [continuous]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Linux runtime dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo rm /etc/apt/sources.list.d/* && sudo dpkg --clear-avail # Speed up installation and get rid of unwanted lists
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsdl2-2.0-0 libpng16-16 libjpeg-turbo8 libopenal1 libmad0 libglew2.1 libgl1 uuid-runtime
      - name: Download continuous es Windows
        if: ${{ matrix.es-build == 'continuous' && matrix.os == 'windows-latest' }}
        run: |
          Invoke-WebRequest https://github.com/endless-sky/endless-sky/releases/download/continuous/EndlessSky-win64-continuous.zip -OutFile es.zip
          New-Item es -ItemType Directory
          Expand-Archive es.zip -DestinationPath es -Force
          Remove-Item es.zip
      - name: Download continuous es Mac
        if: ${{ matrix.es-build == 'continuous' && matrix.os == 'macos-latest' }}
        run: |
          wget -q https://github.com/endless-sky/endless-sky/releases/download/continuous/EndlessSky-macOS-continuous.zip
          unzip EndlessSky-macOS-continuous.zip
          rm EndlessSky-macOS-continuous.zip
      - name: Download continuous es Linux
        if: ${{ matrix.es-build == 'continuous' && matrix.os == 'ubuntu-latest' }}
        run: |
          wget -q https://github.com/endless-sky/endless-sky/releases/download/continuous/endless-sky-x86_64-continuous.tar.gz
          mkdir es
          tar xzf endless-sky-x86_64-continuous.tar.gz -C es
      - name: debugging
        shell: bash
        run: |
          ls
          ls *
          ls */*
      - name: Install dependencies
        run: npm ci
      - run: npm test
